### ISSUE TITLE
Individual category link?

### ISSUE THREAD

**Issue by AndreiJosan** [field-theory/jekyll-category-pages#4]
Hello!
Thanks for this, I managed to make it work very nicely :D.
However, I have a bit of an issue. In the post cards I also display the category of each post and I'd like it to link to the category index page. I cannot manage to get it to work in the forloop I am using to generate the posts. Any idea how the href template should look like?
Thanks a lot!

**Comment by field-theory** [comment]
Hi, thanks for the feedback and your question.

If you have an individual post layout then you could insert the category list including links as follows:
```html
<ul>
{% for category in page.categories %}
<li>
  <a href="{{ site.url }}/path-to-category-index/{{ category | url_encode }}/index.html">{{ category }}</a>
</li>
{% endfor %}
</ul>
```

The reason is the following: Compared to the global category index list (in `example/index.md`) where you loop over the site-wide category list via `site.categories` you must not use `first`. The reason is that when you access the categories on an individual page you just get them from the YAML front matter (just like the plugin does to aggregate the site-wide category list). That means that (i) you access it with `page.categories` and (ii) the individual entries are just strings (and thus different from what you'd get from `site.categories`).

Hope that helps!

**Comment by AndreiJosan** [comment]
This is just what I was looking for.
Thanks a lot for taking the time to explain this to me, it really helped 😀!

**Comment by field-theory** [comment]
Thanks for using this gem and for your feedback. I have included the above description in the README file now and released a minor update with the improved documentation.
