### ISSUE TITLE
category_index.html in theme

### ISSUE THREAD

**Issue by alter-kaker** [field-theory/jekyll-category-pages#7]
Hi,

I am building a website using a homebrewed theme.

When I create the `_layouts/category_index.html` layout file in the theme folder, I get the error: `No such file or directory @ rb_sysopen - [site project path]/_layouts/category_index.html`.

For now I have a symlink from the site project folder to the theme project folder, so I don't have to update two files. 

I am not having any problems with any other layout files.

Thanks for your time!

**Comment by field-theory** [comment]
There seems to be an issue with Jekyll itself, as discussed here: https://github.com/jekyll/jekyll/issues/3248

Basically, under certain circumstances symbolic links to themes don't work. According to the issue discussion this was supposed to be a security "feature", but actually is a bug since the error message does not reveal why the file cannot be found (although it the behavior has been specifically designed as such).

Can you try one of the work-around suggested on that page?

**Comment by alter-kaker** [comment]
I'm going to look more deeply at that thread later, but based on a cursory reading, since the symbolic link is working, I don't think it's the same issue.

What's not working is this: Jekyll normally looks in the theme folder for layouts if the layout is not present in the project folder. All my other layout files are there, and Jekyll is finding them fine without symlinks.
